"""Initial database schema with users, roles, tenants, and tasks

Revision ID: 95f07ecd5e46
Revises: 4b5fc7b428bd
Create Date: 2025-06-02 06:36:21.066540+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f07ecd5e46'
down_revision: Union[str, None] = '4b5fc7b428bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
